#include "core/classify/classifier.hpp"

namespace cleaner::core {

namespace {

Classification safe(DataKind kind, std::string application, std::string what_it_is,
                    std::string reason, std::string consequence, double confidence,
                    std::string cleaner_id = {}) {
    return Classification{
        .content_class = ContentClass::SafeToClean,
        .kind = kind,
        .application = std::move(application),
        .what_it_is = std::move(what_it_is),
        .reason = std::move(reason),
        .consequence = std::move(consequence),
        .confidence = confidence,
        .cleaner_id = std::move(cleaner_id),
    };
}

Classification costly(DataKind kind, std::string application, std::string what_it_is,
                      std::string reason, std::string consequence, double confidence,
                      bool needs_app_closed = false, std::string cleaner_id = {}) {
    return Classification{
        .content_class = ContentClass::CleanWithConsequence,
        .kind = kind,
        .application = std::move(application),
        .what_it_is = std::move(what_it_is),
        .reason = std::move(reason),
        .consequence = std::move(consequence),
        .confidence = confidence,
        .needs_app_closed = needs_app_closed,
        .cleaner_id = std::move(cleaner_id),
    };
}

Classification guarded(DataKind kind, std::string application, std::string what_it_is,
                       std::string reason, double confidence) {
    return Classification{
        .content_class = ContentClass::Protected,
        .kind = kind,
        .application = std::move(application),
        .what_it_is = std::move(what_it_is),
        .reason = std::move(reason),
        .confidence = confidence,
    };
}

Classification review(DataKind kind, std::string application, std::string what_it_is,
                      std::string reason, double confidence) {
    return Classification{
        .content_class = ContentClass::NeedsReview,
        .kind = kind,
        .application = std::move(application),
        .what_it_is = std::move(what_it_is),
        .reason = std::move(reason),
        .confidence = confidence,
    };
}

}

std::vector<ClassificationRule> default_classification_rules() {
    return {
        // --- O que nunca sai, venha de onde vier ---------------------------
        //
        // Primeiro de todos de proposito. Uma pasta de credencial dentro de um
        // perfil de navegador nao pode herdar a classificacao do navegador.
        {{"Credentials"},
         false,
         guarded(DataKind::Credential, {}, "Credenciais guardadas.",
                 "Nome de pasta reservado a credencial em qualquer programa.", 0.9)},
        {{"Login Data"},
         false,
         guarded(DataKind::Credential, {}, "Senhas guardadas pelo navegador.",
                 "Arquivo de senhas do Chromium.", 0.95)},
        {{"Cookies"},
         false,
         guarded(DataKind::Session, {}, "Cookies: e o que mantem voce conectado nos sites.",
                 "Arquivo de sessao do navegador.", 0.9)},
        {{"conversations"},
         false,
         guarded(DataKind::UserContent, {}, "Conversas guardadas.",
                 "Conversa e sessao nunca sao tratadas como cache neste programa.", 0.85)},
        {{"sessions"},
         false,
         guarded(DataKind::Session, {}, "Sessoes guardadas.",
                 "Conversa e sessao nunca sao tratadas como cache neste programa.", 0.85)},

        // --- Navegadores baseados em Chromium ------------------------------
        {{"User Data", "Code Cache"},
         false,
         safe(DataKind::Cache, "Navegador", "Codigo de sites ja compilado, guardado para abrir mais rapido.",
              "Pasta de cache do Chromium, recriada sozinha.",
              "Os sites recompilam na primeira visita. Nenhuma senha, favorito ou historico sai.",
              0.9, "browser.code-cache")},
        {{"User Data", "GPUCache"},
         false,
         safe(DataKind::Cache, "Navegador", "Cache da placa de video usado pelo navegador.",
              "Pasta de cache do Chromium, recriada sozinha.",
              "Recriado no proximo uso.", 0.9, "browser.gpu-cache")},
        {{"User Data", "ShaderCache"},
         false,
         safe(DataKind::Cache, "Navegador", "Shaders compilados pelo navegador.",
              "Pasta de cache do Chromium, recriada sozinha.",
              "Recompilados no proximo uso.", 0.9, "browser.shader-cache")},
        {{"User Data", "Crashpad"},
         false,
         safe(DataKind::Log, "Navegador", "Relatorios de travamento do navegador.",
              "Pasta de relatorio do Chromium.",
              "Perde o material para investigar travamentos passados.", 0.85,
              "browser.crash-reports")},
        {{"User Data", "Cache"},
         false,
         safe(DataKind::Cache, "Navegador", "Paginas e imagens guardadas para carregar mais rapido.",
              "Pasta de cache do Chromium, recriada sozinha.",
              "Os sites carregam um pouco mais devagar na primeira visita. Nenhuma senha, "
              "favorito ou historico sai.",
              0.9, "browser.cache")},

        {{"User Data", "Extensions"},
         false,
         guarded(DataKind::Extension, "Navegador", "Extensoes instaladas.",
                 "Extensao e escolha do usuario, nao sobra de funcionamento.", 0.9)},
        {{"User Data", "IndexedDB"},
         false,
         costly(DataKind::Database, "Navegador", "Dados que os sites guardam para funcionar offline.",
                "Banco de dados de site do Chromium.",
                "Sites que funcionam offline perdem o conteudo guardado e podem pedir login de "
                "novo.",
                0.85, true)},
        {{"User Data", "Local Storage"},
         false,
         costly(DataKind::Database, "Navegador", "Dados que os sites guardam no computador.",
                "Armazenamento local do Chromium.",
                "Alguns sites pedem login de novo e perdem preferencias.", 0.85, true)},
        {{"User Data", "History"},
         false,
         guarded(DataKind::UserContent, "Navegador", "Historico de navegacao.",
                 "Historico e conteudo do usuario.", 0.9)},
        {{"User Data", "Bookmarks"},
         false,
         guarded(DataKind::UserContent, "Navegador", "Favoritos.", "Favorito e conteudo do usuario.",
                 0.95)},
        {{"User Data"},
         false,
         guarded(DataKind::Configuration, "Navegador", "Perfil do navegador.",
                 "Dentro do perfil so saem as pastas de cache reconhecidas uma a uma.", 0.7)},

        // --- Ferramentas de Python -----------------------------------------
        {{"uv", "cache"},
         false,
         costly(DataKind::Package, "Python (uv)", "Pacotes Python ja baixados pelo uv.",
                "Pasta de cache declarada pelo proprio uv.",
                "Nada permanente. O proximo comando que precisar de um pacote baixa outra vez, o "
                "que leva mais tempo e consome internet.",
                0.9, false, "python.uv-cache")},
        {{"pip", "cache"},
         false,
         costly(DataKind::Package, "Python (pip)", "Pacotes Python ja baixados pelo pip.",
                "Pasta de cache declarada pelo proprio pip.",
                "Voltam a ser baixados quando preciso.", 0.9, false, "python.pip-cache")},
        {{"Programs", "Python"},
         false,
         guarded(DataKind::Environment, "Python", "Instalacao do Python.",
                 "Interpretador instalado, nao cache.", 0.9)},
        {{"site-packages"},
         false,
         review(DataKind::Environment, "Python", "Pacotes instalados em um ambiente Python.",
                "Pode ser ambiente de um projeto em uso. Ambiente nunca sai por acao automatica.",
                0.7)},
        {{".venv"},
         false,
         review(DataKind::Environment, "Python", "Ambiente virtual de um projeto.",
                "Ambiente virtual pode pertencer a um projeto ativo; identificar isso exige olhar "
                "o projeto, nao a pasta.",
                0.8)},

        // --- Node e afins ---------------------------------------------------
        {{"npm-cache"},
         false,
         costly(DataKind::Package, "npm", "Pacotes JavaScript ja baixados.",
                "Pasta de cache declarada pelo proprio npm.",
                "Voltam a ser baixados quando preciso.", 0.9, false, "node.npm-cache")},
        {{"Yarn", "Cache"},
         false,
         costly(DataKind::Package, "Yarn", "Pacotes JavaScript ja baixados pelo Yarn.",
                "Pasta de cache declarada pelo proprio Yarn.",
                "Voltam a ser baixados quando preciso.", 0.9, false, "node.yarn-cache")},
        {{"pnpm-store"},
         false,
         costly(DataKind::Package, "pnpm", "Pacotes JavaScript compartilhados entre projetos.",
                "Deposito declarado pelo proprio pnpm.",
                "Voltam a ser baixados quando preciso.", 0.85, false, "node.pnpm-store")},
        {{"node_modules"},
         false,
         review(DataKind::Environment, "Node", "Dependencias instaladas de um projeto.",
                "Pertencem a um projeto especifico. Apagar quebra o projeto ate reinstalar.", 0.8)},

        // --- Outras ferramentas de desenvolvimento --------------------------
        {{".gradle", "caches"},
         false,
         costly(DataKind::Package, "Gradle", "Bibliotecas e resultados de compilacao do Gradle.",
                "Pasta de cache declarada pelo proprio Gradle.",
                "A proxima compilacao baixa e refaz o que precisar, e demora mais.", 0.9, false,
                "dev.gradle-cache")},
        {{".nuget", "packages"},
         false,
         costly(DataKind::Package, "NuGet", "Pacotes .NET ja baixados.",
                "Deposito declarado pelo proprio NuGet.",
                "Voltam a ser baixados quando um projeto precisar.", 0.9, false,
                "dev.nuget-cache")},
        {{".cargo", "registry"},
         false,
         costly(DataKind::Package, "Cargo (Rust)", "Copias das bibliotecas Rust ja baixadas.",
                "Deposito declarado pelo proprio Cargo.",
                "Voltam a ser baixadas quando preciso.", 0.9, false, "dev.cargo-registry")},

        {{"Code", "CachedData"},
         false,
         safe(DataKind::Cache, "Visual Studio Code", "Codigo do editor ja compilado.",
              "Pasta de cache do proprio editor.", "Recriada na proxima abertura.", 0.9,
              "vscode.cached-data")},
        {{"Code", "logs"},
         false,
         safe(DataKind::Log, "Visual Studio Code", "Registros de funcionamento do editor.",
              "Pasta de log do proprio editor.", "Perde o historico de diagnostico do editor.",
              0.9, "vscode.logs")},
        {{"Code", "User"},
         false,
         guarded(DataKind::Configuration, "Visual Studio Code",
                 "Suas configuracoes, atalhos e trechos salvos.",
                 "Configuracao do usuario, nao sobra de funcionamento.", 0.9)},
        {{".vscode", "extensions"},
         false,
         guarded(DataKind::Extension, "Visual Studio Code", "Extensoes instaladas.",
                 "Extensao e escolha do usuario.", 0.9)},

        {{".codex", ".tmp"},
         false,
         safe(DataKind::TemporaryFile, "Codex", "Arquivos de trabalho temporarios.",
              "Pasta de temporario declarada pela propria ferramenta.",
              "Nada do seu historico nem das suas configuracoes, que ficam em outras pastas.",
              0.85, "codex.temporary")},
        {{".codex"},
         false,
         guarded(DataKind::UserContent, "Codex", "Dados da ferramenta, incluindo sessoes.",
                 "Dentro dela so sai o que foi reconhecido um a um.", 0.7)},

        // --- Adobe -----------------------------------------------------------
        {{"Adobe", "Common", "Media Cache Files"},
         false,
         costly(DataKind::Cache, "Adobe", "Previas de audio e video geradas na edicao.",
                "Pasta de cache de midia declarada pela propria Adobe.",
                "O programa gera de novo ao abrir o projeto, o que leva tempo.", 0.9, true,
                "adobe.media-cache")},
        {{"Adobe", "Common", "Media Cache"},
         false,
         costly(DataKind::Cache, "Adobe", "Indices de midia gerados na edicao.",
                "Pasta de cache de midia declarada pela propria Adobe.",
                "O programa gera de novo ao abrir o projeto.", 0.9, true, "adobe.media-cache-db")},
        {{"Adobe", "SpeechESL"},
         false,
         review(DataKind::Package, "Adobe", "Pacotes de idioma da transcricao automatica.",
                "Sao varios idiomas, quase 900 MB cada. Quais estao em uso depende do que voce "
                "transcreve, e o Cleaner nao tem como saber isso.",
                0.75)},
        {{"Adobe", "Presets"},
         false,
         guarded(DataKind::UserContent, "Adobe", "Predefinicoes, suas e de fabrica.",
                 "Preset e conteudo do usuario.", 0.9)},

        // --- Aplicativos Electron -------------------------------------------
        {{"discord", "Cache"},
         false,
         safe(DataKind::Cache, "Discord", "Arquivos guardados para abrir mais rapido.",
              "Pasta de cache do Electron.", "Nao perde conversa nem configuracao.", 0.9,
              "discord.cache")},
        {{"discord", "Code Cache"},
         false,
         safe(DataKind::Cache, "Discord", "Codigo ja compilado do aplicativo.",
              "Pasta de cache do Electron.", "Recompilado na proxima abertura.", 0.9,
              "discord.code-cache")},
        {{"Microsoft", "Teams", "Cache"},
         false,
         safe(DataKind::Cache, "Microsoft Teams", "Arquivos guardados para abrir mais rapido.",
              "Pasta de cache do Electron.", "Nao perde conversa nem configuracao.", 0.85,
              "teams.cache")},

        // --- Windows ---------------------------------------------------------
        {{"Windows", "Temp"},
         false,
         safe(DataKind::TemporaryFile, "Windows", "Arquivos temporarios do sistema.",
              "Pasta que a propria Limpeza de Disco esvazia.",
              "Nada. Programas recriam o que precisarem.", 0.9, "windows.temp")},
        {{"AppData", "Local", "Temp"},
         false,
         safe(DataKind::TemporaryFile, "Windows", "Arquivos temporarios dos seus programas.",
              "Pasta de temporarios do usuario.",
              "Arquivos em uso por programa aberto ficam onde estao.", 0.9, "user.temp")},
        {{"WER", "ReportArchive"},
         false,
         safe(DataKind::Log, "Windows", "Relatorios de erro antigos.",
              "Pasta de relatorio do proprio Windows.",
              "Perde o historico de travamentos antigos.", 0.9, "windows.wer")},
        {{"CrashDumps"},
         false,
         safe(DataKind::Log, "Windows", "Despejos de memoria de programas que travaram.",
              "Pasta de despejo do proprio Windows.",
              "Perde o material para investigar travamentos passados.", 0.9, "windows.crash-dumps")},
        {{"Microsoft", "Windows", "Explorer"},
         false,
         safe(DataKind::Cache, "Windows", "Miniaturas de fotos e videos.",
              "Pasta de miniatura do proprio Explorador.",
              "As miniaturas somem e sao refeitas conforme voce abre as pastas.", 0.9,
              "windows.thumbnails")},
        {{"D3DSCache"},
         false,
         safe(DataKind::Cache, "Windows", "Shaders compilados do DirectX.",
              "Pasta de shader do proprio Windows.", "Recompilados no proximo uso.", 0.9,
              "windows.shader-cache")},
        {{"NVIDIA", "DXCache"},
         false,
         safe(DataKind::Cache, "NVIDIA", "Shaders compilados dos seus jogos.",
              "Pasta de shader do driver.",
              "Os primeiros minutos de cada jogo podem ficar mais lentos.", 0.9, "nvidia.dxcache")},
        {{"NVIDIA", "GLCache"},
         false,
         safe(DataKind::Cache, "NVIDIA", "Shaders OpenGL compilados.", "Pasta de shader do driver.",
              "Recompilados no proximo uso.", 0.9, "nvidia.glcache")},
        {{"SoftwareDistribution", "Download"},
         false,
         costly(DataKind::TemporaryFile, "Windows Update",
                "Instaladores de atualizacao ja aplicados.",
                "Pasta de download do proprio Windows Update.",
                "Se o Windows precisar de novo, ele baixa outra vez.", 0.85, false,
                "windows.update-download")},
        {{"DeliveryOptimization"},
         false,
         safe(DataKind::Cache, "Windows", "Pedacos de atualizacao guardados para compartilhar.",
              "Pasta da Otimizacao de Entrega.", "O Windows baixa de novo se precisar.", 0.85,
              "windows.delivery-optimization")},

        {{"Windows", "Installer"},
         false,
         guarded(DataKind::Installer, "Windows",
                 "Copias dos instaladores dos programas, guardadas pelo Windows.",
                 "Podem ser necessarias para reparar, atualizar ou desinstalar programas. Apagar "
                 "por engano quebra isso, sem volta.",
                 0.9)},
        {{"WinSxS"},
         false,
         guarded(DataKind::SystemComponent, "Windows", "Deposito de componentes do Windows.",
                 "So o DISM mexe aqui. Limpar na mao quebra o Windows.", 0.95)},
        {{"System Volume Information"},
         false,
         guarded(DataKind::SystemComponent, "Windows",
                 "Pontos de restauracao e copias de sombra.",
                 "Area do sistema; a remocao tem caminho oficial proprio.", 0.9)},
        {{"Windows.old"},
         false,
         costly(DataKind::SystemComponent, "Windows", "A instalacao anterior do Windows.",
                "Guardada para permitir voltar a versao anterior.",
                "Depois de remover, nao da mais para voltar a versao anterior do Windows.", 0.9,
                false, "windows.previous-installation")},

        // --- O proprio Cleaner ------------------------------------------------
        {{"Cleaner", "quarentena"},
         false,
         safe(DataKind::TemporaryFile, "Cleaner", "Quarentena de versoes anteriores do Cleaner.",
              "Pasta do proprio programa, de um recurso que nao existe mais.",
              "Nada que o computador use.", 0.95, "cleaner.quarantine")},

        // --- Raizes genericas, por ultimo -------------------------------------
        //
        // Depois de todas as especificas: servem para o que nao casou com nada
        // mais fino nao aparecer como completamente desconhecido, sem por isso
        // ganhar acao nenhuma.
        {{"Packages"},
         false,
         review(DataKind::UserContent, "Aplicativos da Loja",
                "Dados dos aplicativos instalados pela Microsoft Store.",
                "Cada aplicativo guarda o que quer aqui, misturando cache e dado do usuario.",
                0.6)},
        {{"Program Files"},
         false,
         guarded(DataKind::SystemComponent, {}, "Programas instalados.",
                 "Programa instalado sai pela desinstalacao, nao por limpeza de arquivo.", 0.8)},
        {{"Windows"},
         false,
         guarded(DataKind::SystemComponent, "Windows", "Arquivos do sistema.",
                 "Fora dos caminhos com metodo oficial, nada aqui e removido.", 0.7)},
    };
}

}
